[package]
name = "actix-react"
version = "0.1.0"
edition = "2021"

[dependencies]
heisenberg = { path = "../..", features = ["actix"] }
actix-web = "4.0"
tokio = { version = "1.0", features = ["full"] }
serde_json = "1.0"