[workspace]
members = [
    "heisenberg",
    "cargo-heisenberg",
    "examples/*",
]
resolver = "2"

[workspace.package]
version = "0.3.0"
edition = "2021"
rust-version = "1.70"
authors = ["Aaron <aaron@example.com>"]
license = "MIT"
repository = "https://github.com/username/heisenberg"
homepage = "https://github.com/username/heisenberg"
