[package]
name = "logging-example"
version = "0.1.0"
edition = "2021"

[dependencies]
heisenberg = { path = "../..", features = ["logging"] }
axum = "0.7"
tokio = { version = "1.35", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }