[package]
name = "axum-simple"
version = "0.1.0"
edition = "2021"

[dependencies]
heisenberg = { path = "../..", features = ["tower"] }
axum = "0.7"
tokio = { version = "1.0", features = ["full"] }
tower = "0.4"
