name: Coverage

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@cargo-llvm-cov
      - run: >
          cargo llvm-cov --workspace --all-features --lcov --output-path lcov.info
          --exclude actix-react
          --exclude axum-multi-spa
          --exclude axum-sveltekit
          --exclude rocket-multi-spa
          --exclude rocket-vue
      - uses: codecov/codecov-action@v4
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
